import { Platform, StyleSheet } from "react-native";

import {
  createEditorialPalette,
  createEditorialStyles,
  editorialOverlay,
} from "@/theme/editorial-theme";
import { Type } from "@/theme/typography";

const Palette = createEditorialPalette(() => ({
  overlay: editorialOverlay(0.42),
}));

export const controlStyles = createEditorialStyles(() => ({
  safe: { flex: 1, backgroundColor: Palette.background },
  screen: { flex: 1 },
  content: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === "ios" ? 90 : 78,
    gap: 16,
  },
  statusCard: {
    backgroundColor: Palette.inverse,
    borderRadius: 8,
    padding: 16,
    gap: 12,
  },
  statusTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modeIdentity: { flexDirection: "row", alignItems: "center", gap: 12 },
  modeIcon: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: Palette.red,
    alignItems: "center",
    justifyContent: "center",
  },
  statusLabel: { ...Type.label, color: Palette.muted },
  modeTitle: { ...Type.titleLarge, color: Palette.onInverse },
  clock: {
    ...Type.bodyStrong,
    color: Palette.secondary,
    fontVariant: ["tabular-nums"],
  },
  statusDetail: { ...Type.body, color: Palette.secondary },
  metricRow: {
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: Palette.inverseLine,
    paddingVertical: 12,
  },
  metric: { flex: 1 },
  metricValue: { ...Type.metric, color: Palette.onInverse },
  metricLabel: { ...Type.label, color: Palette.muted, marginTop: 3 },
  metricDivider: {
    width: 1,
    height: 30,
    backgroundColor: Palette.inverseLine,
    marginHorizontal: 16,
  },
  primaryButton: {
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: Palette.red,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 18,
  },
  primaryButtonText: { ...Type.button, color: Palette.onAccent },
  sessionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sessionTime: { ...Type.displayNumber, color: Palette.onInverse },
  secondaryButton: {
    minHeight: 44,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    paddingHorizontal: 16,
  },
  secondaryButtonText: { ...Type.buttonSmall, color: Palette.onInverse },
  restDismissButtonText: {
    ...Type.buttonSmall,
    color: Palette.ink,
    textAlign: "center",
  },
  sectionHeader: {
    minHeight: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionLabel: { ...Type.label, color: Palette.muted },
  textAction: { ...Type.buttonSmall, color: Palette.red },
  timelineCard: {
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    padding: 16,
    gap: 9,
    backgroundColor: Palette.card,
  },
  timelineTrack: {
    height: 28,
    borderRadius: 6,
    backgroundColor: Palette.surface,
    overflow: "hidden",
    position: "relative",
  },
  timelineFocus: {
    position: "absolute",
    top: 0,
    bottom: 0,
    backgroundColor: Palette.red,
  },
  timelineSleep: {
    position: "absolute",
    top: 0,
    bottom: 0,
    backgroundColor: Palette.blue,
  },
  hourRow: { flexDirection: "row", justifyContent: "space-between" },
  hour: { ...Type.microLabel, color: Palette.muted },
  legend: { flexDirection: "row", gap: 15, marginTop: 4 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  legendDot: { width: 7, height: 7, borderRadius: 2 },
  legendText: { ...Type.caption, color: Palette.secondary },
  appearanceCard: {
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 10,
    padding: 15,
    gap: 12,
    backgroundColor: Palette.card,
  },
  appearanceHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingBottom: 2,
  },
  appearanceIcon: {
    width: 40,
    height: 40,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Palette.redSoft,
  },
  appearanceCopy: { flex: 1 },
  appearanceTitle: { ...Type.bodyStrong, color: Palette.ink },
  appearanceDetail: { ...Type.bodySmall, color: Palette.secondary, marginTop: 2 },
  appearanceFieldLabel: { ...Type.label, color: Palette.muted, marginTop: 2 },
  appearanceModeRow: { flexDirection: "row", gap: 8 },
  appearanceMode: {
    flex: 1,
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    backgroundColor: Palette.surface,
  },
  appearanceModeActive: {
    borderColor: Palette.red,
    backgroundColor: Palette.red,
  },
  appearanceModeText: { ...Type.buttonSmall, color: Palette.secondary },
  appearanceModeTextActive: { color: Palette.onAccent },
  accentGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  accentOption: {
    width: "48.7%",
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    paddingHorizontal: 10,
    backgroundColor: Palette.surface,
  },
  accentOptionActive: {
    borderColor: Palette.red,
    backgroundColor: Palette.redSoft,
  },
  accentSwatch: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  accentCopy: { flex: 1, minWidth: 0 },
  accentName: { ...Type.buttonSmall, color: Palette.ink },
  accentDescription: { ...Type.microLabel, color: Palette.muted, marginTop: 2 },
  menuCard: {
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    overflow: "hidden",
  },
  menuRow: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    gap: 13,
    backgroundColor: Palette.card,
  },
  menuBorder: { borderTopWidth: 1, borderTopColor: Palette.line },
  menuIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: Palette.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  menuCopy: { flex: 1, gap: 3 },
  menuTitle: { ...Type.bodyStrong, color: Palette.ink },
  menuDetail: { ...Type.bodySmall, color: Palette.secondary },
  editorModalRoot: { flex: 1, justifyContent: "flex-end" },
  editorBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: Palette.overlay,
  },
  editorSheet: {
    width: "100%",
    maxWidth: 760,
    maxHeight: "88%",
    alignSelf: "center",
    backgroundColor: Palette.card,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    overflow: "hidden",
  },
  editorDragArea: { paddingTop: 0 },
  editorGrabArea: { height: 44, justifyContent: 'center' },
  editorHandle: {
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#D2D2D2",
    alignSelf: "center",
  },
  editorHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 22,
    paddingTop: 17,
    paddingBottom: 18,
    gap: 12,
  },
  editorTitleGroup: { flex: 1 },
  editorEyebrow: { ...Type.label, color: Palette.red, marginBottom: 5 },
  editorTitle: { ...Type.heroTitle, color: Palette.ink },
  editorSubtitle: { ...Type.body, color: Palette.secondary, marginTop: 3 },
  editorBody: { flexShrink: 1, overflow: "hidden" },
  editorContent: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 22,
    paddingBottom: 34,
    gap: 16,
  },
  pressed: { opacity: 0.65 },
  searchBox: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderRadius: 8,
    backgroundColor: Palette.surface,
    paddingHorizontal: 14,
  },
  searchInput: {
    ...Type.input,
    flex: 1,
    color: Palette.ink,
    paddingVertical: 12,
  },
  selectionCount: { ...Type.label, color: Palette.secondary },
  appRowWrap: {
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: Palette.card,
  },
  appRow: {
    minHeight: 66,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 13,
    gap: 12,
  },
  appMark: { borderRadius: 8, alignItems: "center", justifyContent: "center" },
  appCopy: { flex: 1 },
  appName: { ...Type.bodyStrong, color: Palette.ink },
  appCategory: { ...Type.caption, color: Palette.secondary, marginTop: 2 },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: "#BEBEBE",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxSelected: { backgroundColor: Palette.red, borderColor: Palette.red },
  limitEditor: {
    borderTopWidth: 1,
    borderTopColor: Palette.line,
    backgroundColor: Palette.surface,
    padding: 13,
    gap: 9,
  },
  limitLabel: { ...Type.label, color: Palette.secondary },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  chip: {
    minHeight: 38,
    minWidth: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Palette.line,
    backgroundColor: Palette.card,
  },
  chipActive: { borderColor: Palette.red, backgroundColor: Palette.redSoft },
  chipText: { ...Type.buttonSmall, color: Palette.secondary },
  chipTextActive: { color: Palette.red },
  customLimit: {
    height: 38,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    backgroundColor: Palette.card,
    paddingHorizontal: 9,
  },
  limitInput: {
    ...Type.bodyStrong,
    minWidth: 36,
    color: Palette.ink,
    textAlign: "right",
    paddingVertical: 7,
  },
  unit: { ...Type.caption, color: Palette.muted },
  emptyState: { alignItems: "center", paddingVertical: 32, gap: 6 },
  emptyTitle: { ...Type.cardTitle, color: Palette.ink },
  emptyCopy: {
    ...Type.bodySmall,
    color: Palette.secondary,
    textAlign: "center",
  },
  formCard: {
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    padding: 15,
    gap: 14,
    backgroundColor: Palette.card,
  },
  formCardError: { borderColor: Palette.red },
  formHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  formTitle: { ...Type.cardTitle, color: Palette.ink },
  formMeta: { ...Type.caption, color: Palette.secondary, marginTop: 3 },
  timeRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  field: { flex: 1, gap: 5 },
  fieldLabel: { ...Type.label, color: Palette.muted },
  timeInput: {
    ...Type.cardTitle,
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: Palette.surface,
    paddingHorizontal: 12,
    color: Palette.ink,
  },
  blockName: {
    ...Type.cardTitle,
    flex: 1,
    color: Palette.ink,
    paddingVertical: 8,
  },
  deleteButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  errorText: { ...Type.captionStrong, color: Palette.red },
  validText: { ...Type.captionStrong, color: Palette.secondary },
  focusHero: { alignItems: "center", paddingVertical: 18, gap: 8 },
  focusHeroIcon: {
    width: 60,
    height: 60,
    borderRadius: 20,
    backgroundColor: Palette.redSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  focusHeroTitle: { ...Type.titleLarge, color: Palette.ink, marginTop: 4 },
  focusHeroCopy: {
    ...Type.bodySmall,
    maxWidth: 330,
    color: Palette.secondary,
    textAlign: "center",
  },
  durationGrid: { flexDirection: "row", gap: 9 },
  durationButton: {
    flex: 1,
    minHeight: 88,
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Palette.card,
  },
  durationButtonActive: {
    borderColor: Palette.red,
    backgroundColor: Palette.redSoft,
  },
  durationValue: { ...Type.modalTitle, color: Palette.ink },
  durationUnit: { ...Type.microLabel, color: Palette.muted },
  durationValueActive: { color: Palette.red },
  customDurationRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: Palette.line,
    paddingTop: 16,
  },
  modeTabs: {
    flexDirection: "row",
    backgroundColor: Palette.surface,
    borderRadius: 8,
    padding: 4,
    gap: 3,
  },
  modeTab: {
    flex: 1,
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 6,
  },
  modeTabActive: { backgroundColor: Palette.red },
  modeTabText: { ...Type.buttonSmall, color: Palette.secondary },
  modeTabTextActive: { color: Palette.onAccent },
  settingsCard: {
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: Palette.card,
  },
  settingRow: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 13,
    gap: 11,
  },
  settingIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: Palette.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  minuteField: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: Palette.surface,
    paddingHorizontal: 10,
  },
  minuteInput: {
    ...Type.cardTitle,
    flex: 1,
    color: Palette.ink,
    paddingVertical: 10,
  },
  allowedRow: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 13,
    gap: 11,
  },
  allowedName: { flex: 1 },
  infoCard: {
    flexDirection: "row",
    gap: 10,
    backgroundColor: Palette.surface,
    borderRadius: 8,
    padding: 14,
  },
  infoText: { ...Type.bodySmall, flex: 1, color: Palette.secondary },
  nativeSwitch: { transform: [{ scale: 0.86 }] },
}));
