import { Platform, StyleSheet } from "react-native";

import {
  EditorialColors,
  editorialOverlay,
} from "../../constants/editorial-theme";
import { Type } from "../../constants/typography";

const Palette = {
  ...EditorialColors,
  overlay: editorialOverlay(0.42),
};

export const protectStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Palette.white },
  screen: { flex: 1 },
  content: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === "ios" ? 90 : 78,
    gap: 16,
  },
  header: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: Palette.line,
  },
  eyebrow: { ...Type.bodySmall, color: Palette.secondary, marginTop: 3 },
  title: { ...Type.pageTitle, color: Palette.ink },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  headerAction: {
    height: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 13,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#F4C8CC",
    backgroundColor: Palette.redSoft,
  },
  headerActionActive: {
    borderColor: Palette.red,
    backgroundColor: Palette.red,
  },
  headerActionText: { ...Type.buttonSmall, color: Palette.red },
  headerActionTextActive: { color: Palette.white },
  headerIconButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: Palette.line,
    backgroundColor: Palette.white,
  },
  statusCard: {
    backgroundColor: Palette.ink,
    borderRadius: 8,
    padding: 16,
    gap: 12,
  },
  statusTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modeIdentity: { flexDirection: "row", alignItems: "center", gap: 12 },
  modeIcon: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: Palette.red,
    alignItems: "center",
    justifyContent: "center",
  },
  statusLabel: { ...Type.label, color: "#AFAFAF" },
  modeTitle: { ...Type.titleLarge, color: Palette.white },
  clock: {
    ...Type.bodyStrong,
    color: "#C7C7C7",
    fontVariant: ["tabular-nums"],
  },
  statusDetail: { ...Type.body, color: "#D2D2D2" },
  metricRow: {
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#353535",
    paddingVertical: 12,
  },
  metric: { flex: 1 },
  metricValue: { ...Type.metric, color: Palette.white },
  metricLabel: { ...Type.label, color: "#8F8F8F", marginTop: 3 },
  metricDivider: {
    width: 1,
    height: 30,
    backgroundColor: "#353535",
    marginHorizontal: 16,
  },
  primaryButton: {
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: Palette.red,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 18,
  },
  primaryButtonText: { ...Type.button, color: Palette.white },
  sessionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sessionTime: { ...Type.displayNumber, color: Palette.white },
  secondaryButton: {
    minHeight: 44,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#555",
    borderRadius: 8,
    paddingHorizontal: 16,
  },
  secondaryButtonText: { ...Type.buttonSmall, color: Palette.white },
  sectionHeader: {
    minHeight: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionLabel: { ...Type.label, color: Palette.muted },
  textAction: { ...Type.buttonSmall, color: Palette.red },
  timelineCard: {
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    padding: 16,
    gap: 9,
  },
  timelineTrack: {
    height: 28,
    borderRadius: 6,
    backgroundColor: Palette.surface,
    overflow: "hidden",
    position: "relative",
  },
  timelineFocus: {
    position: "absolute",
    top: 0,
    bottom: 0,
    backgroundColor: Palette.red,
  },
  timelineSleep: {
    position: "absolute",
    top: 0,
    bottom: 0,
    backgroundColor: Palette.blue,
  },
  hourRow: { flexDirection: "row", justifyContent: "space-between" },
  hour: { ...Type.microLabel, color: Palette.muted },
  legend: { flexDirection: "row", gap: 15, marginTop: 4 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  legendDot: { width: 7, height: 7, borderRadius: 2 },
  legendText: { ...Type.caption, color: Palette.secondary },
  menuCard: {
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    overflow: "hidden",
  },
  menuRow: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    gap: 13,
    backgroundColor: Palette.white,
  },
  menuBorder: { borderTopWidth: 1, borderTopColor: Palette.line },
  menuIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: Palette.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  menuCopy: { flex: 1, gap: 3 },
  menuTitle: { ...Type.bodyStrong, color: Palette.ink },
  menuDetail: { ...Type.bodySmall, color: Palette.secondary },
  editorModalRoot: { flex: 1, justifyContent: "flex-end" },
  editorBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Palette.overlay,
  },
  editorSheet: {
    width: "100%",
    maxWidth: 760,
    maxHeight: "88%",
    alignSelf: "center",
    backgroundColor: Palette.white,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    overflow: "hidden",
  },
  editorHandle: {
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#D2D2D2",
    alignSelf: "center",
    marginTop: 9,
  },
  editorHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 22,
    paddingTop: 17,
    paddingBottom: 18,
    gap: 12,
  },
  editorTitleGroup: { flex: 1 },
  editorEyebrow: { ...Type.label, color: Palette.red, marginBottom: 5 },
  editorTitle: { ...Type.heroTitle, color: Palette.ink },
  editorSubtitle: { ...Type.body, color: Palette.secondary, marginTop: 3 },
  editorClose: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: Palette.line,
    alignItems: "center",
    justifyContent: "center",
  },
  editorBody: { flexShrink: 1, overflow: "hidden" },
  editorContent: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    paddingHorizontal: 22,
    paddingBottom: 34,
    gap: 16,
  },
  pressed: { opacity: 0.65 },
  searchBox: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderRadius: 8,
    backgroundColor: Palette.surface,
    paddingHorizontal: 14,
  },
  searchInput: {
    ...Type.input,
    flex: 1,
    color: Palette.ink,
    paddingVertical: 12,
  },
  selectionCount: { ...Type.label, color: Palette.secondary },
  appRowWrap: {
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    overflow: "hidden",
  },
  appRow: {
    minHeight: 66,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 13,
    gap: 12,
  },
  appMark: { borderRadius: 8, alignItems: "center", justifyContent: "center" },
  appCopy: { flex: 1 },
  appName: { ...Type.bodyStrong, color: Palette.ink },
  appCategory: { ...Type.caption, color: Palette.secondary, marginTop: 2 },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: "#BEBEBE",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxSelected: { backgroundColor: Palette.red, borderColor: Palette.red },
  limitEditor: {
    borderTopWidth: 1,
    borderTopColor: Palette.line,
    backgroundColor: Palette.surface,
    padding: 13,
    gap: 9,
  },
  limitLabel: { ...Type.label, color: Palette.secondary },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 7 },
  chip: {
    minHeight: 38,
    minWidth: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Palette.line,
    backgroundColor: Palette.white,
  },
  chipActive: { borderColor: Palette.red, backgroundColor: Palette.redSoft },
  chipText: { ...Type.buttonSmall, color: Palette.secondary },
  chipTextActive: { color: Palette.red },
  customLimit: {
    height: 38,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    backgroundColor: Palette.white,
    paddingHorizontal: 9,
  },
  limitInput: {
    ...Type.bodyStrong,
    minWidth: 36,
    color: Palette.ink,
    textAlign: "right",
    paddingVertical: 7,
  },
  unit: { ...Type.caption, color: Palette.muted },
  emptyState: { alignItems: "center", paddingVertical: 32, gap: 6 },
  emptyTitle: { ...Type.cardTitle, color: Palette.ink },
  emptyCopy: {
    ...Type.bodySmall,
    color: Palette.secondary,
    textAlign: "center",
  },
  formCard: {
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    padding: 15,
    gap: 14,
  },
  formCardError: { borderColor: "#E8A3AA" },
  formHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  formTitle: { ...Type.cardTitle, color: Palette.ink },
  formMeta: { ...Type.caption, color: Palette.secondary, marginTop: 3 },
  timeRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  field: { flex: 1, gap: 5 },
  fieldLabel: { ...Type.label, color: Palette.muted },
  timeInput: {
    ...Type.cardTitle,
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: Palette.surface,
    paddingHorizontal: 12,
    color: Palette.ink,
  },
  blockName: {
    ...Type.cardTitle,
    flex: 1,
    color: Palette.ink,
    paddingVertical: 8,
  },
  deleteButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  errorText: { ...Type.captionStrong, color: Palette.red },
  validText: { ...Type.captionStrong, color: Palette.secondary },
  focusHero: { alignItems: "center", paddingVertical: 18, gap: 8 },
  focusHeroIcon: {
    width: 60,
    height: 60,
    borderRadius: 20,
    backgroundColor: Palette.redSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  focusHeroTitle: { ...Type.titleLarge, color: Palette.ink, marginTop: 4 },
  focusHeroCopy: {
    ...Type.bodySmall,
    maxWidth: 330,
    color: Palette.secondary,
    textAlign: "center",
  },
  durationGrid: { flexDirection: "row", gap: 9 },
  durationButton: {
    flex: 1,
    minHeight: 88,
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Palette.white,
  },
  durationButtonActive: {
    borderColor: Palette.red,
    backgroundColor: Palette.redSoft,
  },
  durationValue: { ...Type.modalTitle, color: Palette.ink },
  durationUnit: { ...Type.microLabel, color: Palette.muted },
  durationValueActive: { color: Palette.red },
  customDurationRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: Palette.line,
    paddingTop: 16,
  },
  modeTabs: {
    flexDirection: "row",
    backgroundColor: Palette.surface,
    borderRadius: 8,
    padding: 4,
    gap: 3,
  },
  modeTab: {
    flex: 1,
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 6,
  },
  modeTabActive: { backgroundColor: Palette.red },
  modeTabText: { ...Type.buttonSmall, color: Palette.secondary },
  modeTabTextActive: { color: Palette.white },
  settingsCard: {
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: 8,
    overflow: "hidden",
  },
  settingRow: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 13,
    gap: 11,
  },
  settingIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: Palette.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  minuteField: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: Palette.surface,
    paddingHorizontal: 10,
  },
  minuteInput: {
    ...Type.cardTitle,
    flex: 1,
    color: Palette.ink,
    paddingVertical: 10,
  },
  allowedRow: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 13,
    gap: 11,
  },
  allowedName: { flex: 1 },
  infoCard: {
    flexDirection: "row",
    gap: 10,
    backgroundColor: Palette.surface,
    borderRadius: 8,
    padding: 14,
  },
  infoText: { ...Type.bodySmall, flex: 1, color: Palette.secondary },
  toggleTrack: {
    width: 42,
    height: 24,
    borderRadius: 12,
    backgroundColor: Palette.line,
    padding: 3,
    justifyContent: "center",
  },
  toggleTrackActive: { backgroundColor: Palette.red },
  toggleThumb: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: Palette.white,
    borderWidth: 1,
    borderColor: "#D4D4D4",
  },
  toggleThumbActive: {
    transform: [{ translateX: 18 }],
    borderColor: Palette.white,
  },
});
